# Generated by Django 4.0.4 on 2022-04-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_candidates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidates',
            options={'verbose_name_plural': 'Candidates'},
        ),
    ]
