# Generated by Django 4.0.4 on 2022-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_alter_candidates_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
