# Generated by Django 4.0.4 on 2022-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_voter_is_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
